tasks:
  - init: mvn install -DskipTests jetty:run

    command: mvn
ports:
  - port: 8080
    onOpen: open-preview
github:
  prebuilds:
    # enable prebuilds for all branches in this repo
    branches: true